### ISSUE TITLE
Rename number to name in web

### ISSUE THREAD

**Issue by rizwansoaib** [rizwansoaib/whatsapp-monitor#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by malaguer** [comment]
Hi @rizwansoaib, I created a userscript that I use with Tampermonkey, for personal use, to solve this problem.

It has no interface (to add numbers and names and avatars) to interact easily with it. I edit the code by myself when I need to add contacts. That's why I didn't published it. But it does its job very well for me.

Do you think that a userscript like this could be helpful for you?

**Comment by malaguer** [comment]
> I have worked already on telegram api so I will do it easily.

I think you've maybe confused the answer with this other issue #149 ?

I was answering to the Rename Numbers in analytics website issue... :-/

**Comment by rizwansoaib** [comment]
Sorry I saw mail only a d reply from mail.


Ok but soon website domain will expire end of FEB.

And I need to rewrite backend I will do it when updating it on new servers.

**Comment by malaguer** [comment]
> Ok but soon website domain will expire end of FEB.
> 
> And I need to rewrite backend I will do it when updating it on new servers.

Ok. Then I'll wait till you set up the new backend. When I see how it's working and check the new interface, I'll see If there is something that I could help with.

Thanks for your efforts.  :)

Regards.
