### ISSUE TITLE
NoSuchElementException: Message: no such element: Unable to locate element

### ISSUE THREAD

**Issue by elanozturk** [rizwansoaib/whatsapp-monitor#4]
Hi,i get this error:

./monitor+log.py 
Please Wait Starting whatsapp-monitor
QR Code Generating
Traceback (most recent call last):
  File "./monitor+log.py", line 37, in <module>
    file.write(driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/img').screenshot_as_png)
  File "/home/elan/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/elan/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/elan/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/elan/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/img"}
  (Session info: headless chrome=78.0.3904.108)

**Comment by rizwansoaib** [comment]
Before this use sleep(30)


e.g.- 
sleep(30)
with open('qr.png', 'wb') as file: 
file.write(driver.find_element_by_xpath('/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/img').screenshot_as_png)


Actually it's error because your http://web.whatsapp.com not loaded 100% so using sleep after 20sec webpage will loaded successfully.


Please open web.whatsapp.com in your browser and check how many seconds it's take time to load 
then enter in sleep()

Well in monitor+log.py I added 30sec.


Thank You

**Comment by elanozturk** [comment]
i tried also; wait = WebDriverWait(driver, 600) and sleep after open issue but no luck, i use chrome instead of firefox, when i changed headless mode to the False, it worked but appeared 2 qr code on screen (imagemagick and on page)

**Comment by rizwansoaib** [comment]
when headless=False remove Qr code generation code
